version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.code.findbugs:annotations
    versions:
    - "> 3.0.1, < 3.1"
  - dependency-name: com.commercetools:commercetools-sync-java
    versions:
    - 4.2.0
    - 5.0.0
    - 5.1.0
